# Generates a Version.h file.
cmake_minimum_required(VERSION 3.10)

execute_process(
    COMMAND 
        git describe --tags --long 
    OUTPUT_VARIABLE
        BUILD_VERSION
)

#message("BUILD_VERSION: ${BUILD_VERSION}")
string(STRIP "${BUILD_VERSION}" BUILD_VERSION)
set(PROJECT_VERSION "${BUILD_VERSION}")

string(REGEX REPLACE "^v" "" BUILD_VERSION ${BUILD_VERSION})
string(REGEX MATCH "^([0-9]+)" MAJOR_VERSION ${BUILD_VERSION})
string(REGEX REPLACE "^${MAJOR_VERSION}\\." "" BUILD_VERSION ${BUILD_VERSION})
string(REGEX MATCH "^([0-9]+)" MINOR_VERSION ${BUILD_VERSION})
string(REGEX REPLACE "^${MINOR_VERSION}\\-" "" BUILD_VERSION ${BUILD_VERSION})
string(REGEX MATCH "^([0-9]+)" NUM_COMMITS ${BUILD_VERSION})
string(REGEX REPLACE "^${NUM_COMMITS}\\-" "" COMMIT_HASH ${BUILD_VERSION})
string(STRIP "${COMMIT_HASH}" COMMIT_HASH)

message("PROJECT_VERSION: ${PROJECT_VERSION} ")
message("MAJOR_VERSION: ${MAJOR_VERSION}")
message("MINOR_VERSION: ${MINOR_VERSION}")
message("NUM_COMMITS: ${NUM_COMMITS}")
message("COMMIT_HASH: ${COMMIT_HASH}")

configure_file(Version.h.in Version.h @ONLY)